### ISSUE TITLE
error in docker-compose

### ISSUE THREAD

**Issue by onepushmain** [AcompanhaLegis/acompanha-legis-api#14]
when I run the comand `$ docker-compose -f docker-compose.dev.yml up` the container start to install, but when it load the /.setup.py install, I got a "not found" error:
```
...
(30/30) Installing build-dependencies (20201007.144957)
Executing busybox-1.31.1-r16.trigger
OK: 358 MiB in 65 packages
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (20.2.3)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/site-packages (50.3.0)
/bin/sh: ./setup.py: not found
ERROR: Service 'api' failed to build : The command '/bin/sh -c apk update && apk --no-cache add --virtual build-dependencies     
gcc     musl-dev     postgresql-dev     tzdata &&    pip install -U pip setuptools &&    ./setup.py install &&    api collectstatic &&    rm -rf /opt/acompanha_legis/*' returned a non-zero code: 127
```

Did I miss something?

**Comment by BrunaNayara** [comment]
Before running the compose up command, did you run this one here? 
```$ cp .env.example .env```

**Comment by onepushmain** [comment]
Yes! Im using **Windows 10 with WSL2**, so I copy this and put in the same directory, like this: 

![image](https://user-images.githubusercontent.com/22600730/95365617-c35b4a80-08a8-11eb-9db6-ed88e7e3854d.png)

and, when I run `$ docker-compose -f docker-compose.dev.yml up` in the directory, I got the same error:

![image](https://user-images.githubusercontent.com/22600730/95365838-061d2280-08a9-11eb-9e72-2f831fbd11e9.png)

**Comment by BrunaNayara** [comment]
:thinking: I've never tried running it on windows. Later today I'll take o look at it more closely. 
Thanks for the screenshots.

**Comment by onepushmain** [comment]
I'm gonna try to debug this too :) I'll Publish here and make a PR if i fixed it

**Comment by kimuraz** [comment]
@Tawliew can you take a look at this https://github.com/docker/compose/issues/4240? May be related...
Long story short, add `COMPOSE_CONVERT_WINDOWS_PATHS=1` on your `.env` 😬 
Let us know!

**Comment by BrunaNayara** [comment]
There is a branch with this change.  [fix-compose-windows](https://github.com/AcompanhaLegis/acompanha-legis-api/tree/fix-compose-windows)

If you prefer, you can checkout and test it. If it works, please let us know

**Comment by onepushmain** [comment]
Hi again @BrunaNayara @kimuraz!

So... Its gonna be a big text: 
First, I cloned the repository with the branch of the fix. After, I tried to install, but I had the same error.
I decided to change the DockerFile into `acompanha-legis-api\api\`, and change this code :
 `RUN apk update && apk --no-cache add --virtual build-dependencies \
    gcc \
    musl-dev \
    postgresql-dev \
    tzdata &&\
    pip install -U pip setuptools &&\
    ./setup.py install &&\
    api collectstatic &&\
    rm -rf /opt/acompanha_legis/*`  
    to this:
`RUN  pip  install  -U  pip  setuptools`
`CMD  [  "python",  "./setup.py"  ]`
`CMD  [  "python",  "api  collectstatic"  ]`
`RUN  rm  -rf  /opt/acompanha_legis/*`

 I change too the DockerFile in `acompanha-legis-api\acompanha_legis\`to:
 
 `RUN  apk  update  &&  apk  --no-cache  add  --virtual  build-dependencies \
gcc \
musl-dev \
postgresql-dev \
tzdata`

`RUN  pip  install  -U  pip  setuptools`

`CMD  [  "python",  "./setup.py"  ]`

`RUN  rm  -rf  /opt/acompanha_legis/*`

After this, the installation was going well, when it happens: 


![after-commands-execution](https://user-images.githubusercontent.com/22600730/95487588-e51d0600-096a-11eb-93fb-1289b001a826.png)
![after-commands-execution-without-pwd](https://user-images.githubusercontent.com/22600730/95487529-d46c9000-096a-11eb-8eb1-30ab1372d0ed.png)



and now I'm stucked here ... T.T 
I will keep trying to test and "debug" this!
If you know someone who have used docker-cointainer on an Windows in this project, please, let me know this! :)

OBS: The Docker status in windows:
![docker-status](https://user-images.githubusercontent.com/22600730/95487721-1269b400-096b-11eb-8f28-6729e05f3972.png)

**Comment by BrunaNayara** [comment]
@Tawliew I think we can get the api is running, even if the tasks are not.

Can you try running `$ docker-compose -f docker-compose.dev.yml up api`
If this works, you will get the api container running and will be able to test it.

For what we are doing with the tasks, they are not necessary to run and contribute to the api. (It is a legacy we will try to break to pieces and incorporate into the project)

**Comment by BrunaNayara** [comment]
Oh, @Tawliew one more thing. 
I think the changes you made to the dockerfile are great. Can you open a PR with it so we can review it?

**Comment by onepushmain** [comment]
@BrunaNayara I try running `$ docker-compose -f docker-compose.dev.yml up api`  and get this: 

![django error](https://user-images.githubusercontent.com/22600730/95601028-54592f80-0a29-11eb-9227-b3595626cca3.png)

So, i add one line in each of the DockerFiles, with `RUN pip install Django`

![add-line-django-dockerfile](https://user-images.githubusercontent.com/22600730/95601222-8cf90900-0a29-11eb-9773-3a24085141f8.png)

After, the docker  acompanha-legis-api_api_1 start to running 🎉

![docker-windows](https://user-images.githubusercontent.com/22600730/95601512-ecefaf80-0a29-11eb-8009-1013352aabef.png)

but, when i run the same  `$ docker-compose -f docker-compose.dev.yml up api` , i get: 

![error-after-import-django](https://user-images.githubusercontent.com/22600730/95602028-bd8d7280-0a2a-11eb-99a7-aa73e75a5847.png)


But as was I saying, the image was running. So, I tried to run `$ yarn dev` in the `/camara-data-portal` folder... and get this:

![site error](https://user-images.githubusercontent.com/22600730/95601823-68e9f780-0a2a-11eb-8401-31fdbc24b7c2.png)

![console_error_site](https://user-images.githubusercontent.com/22600730/95602222-fdecf080-0a2a-11eb-9b31-9e4bceffb3a1.png)

I gonna PR my changes in the acompanha-legis-api, but I think it still not working. Thank You!

OBS: (I'm starting in this world of open source and I don't know much about docker and vue, so the probability that i made a mistake is high. So, my apologies)

OBS: Later, I'll try to run in a VM with ubuntu, to fix that card in frontend.

**Comment by BrunaNayara** [comment]
I think you are doing great in starting into the free open source sowftware. 
I will dive into your PR and test it. Thank you again :) 

The idea of the dev docker compose is to be able to run the api, without the frontend. But if you are going to try to work on the fronted, it's even better :D

**Comment by kimuraz** [comment]
@Tawliew Hey, sorry to take that long, the windows setup is pretty new for me, but after setting docker on windows I could fix the problem. Can you check on this branch? https://github.com/AcompanhaLegis/acompanha-legis-api/pull/26

**Comment by onepushmain** [comment]
I checked and worked for me! Thanks!

![image](https://user-images.githubusercontent.com/22600730/95770249-7fdd5380-0c8f-11eb-8d99-2fa4bb24ca46.png)

**Obs:** As I'm on a trip at the moment, I still haven't been able to try using the camara-data-portal. When I try this, I send feedback :)

**Comment by kimuraz** [comment]
@Tawliew sure, glad that it worked, enjoy your trip! 👍
