### ISSUE TITLE
Change url 'reset_password' to 'change_password'

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/acompanha-legis-api#4]
# Problem
Currently, the 'reset_password' actually is to change password when the user is logged.

# Solution
[Change url](https://github.com/AcompanhaLegis/acompanha-legis-api/blob/master/api/api/urls.py#L39)

## Tasks
- [ ] change url

**Comment by theopaid** [comment]
Hi! I'll make a PR on Oct 1st for HacktoberFest :)

**Comment by BrunaNayara** [comment]
@theopaid Nice! Thanks!
